# Day 3 Assignment

Question 1:

In [2]:
import numpy as np
arr = np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


Question 2:

In [4]:
a = list(input("enter 5 elements").split())
b = list(input("enter 5 elements").split())
a=np.array(a)
b=np.array(b)
c=np.concatenate((a,b))
print(c)
a = np.sort(a)
print(a)

enter 5 elements1 2 3 4 5
enter 5 elements6 7 8 9 10
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']
['1' '2' '3' '4' '5']


Question 3:

In [5]:
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]],[[2, 4, 5],[5, 6, 7]]])

print(b.ndim)
print(c.ndim)
print(d.ndim)
print(b.size)
print(c.size)
print(d.size)

1
2
3
5
6
12


Question 4:

In [8]:
arr = np.array([1,2,4,5,6])
arr = np.expand_dims(arr,axis=(0,1))
print(arr)

[[[1 2 4 5 6]]]


Question 5:

In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


Question 6:

In [10]:
x = np.array([1,1,1,2,2,2,5,2,1,1,3])
unique, counts = np.unique(x, return_counts=True)
print(np.asarray((unique, counts)).T)

[[1 5]
 [2 4]
 [3 1]
 [5 1]]
